# set line length
line-length = 80
# set indentation width
indent-width = 4

# always generate python 3.12-compatible code
target-version = "py312"

[format]
# use single quotes for strings
quote-style = "single"
# ensure indentation is done with spaces
indent-style = "space"

[lint.flake8-import-conventions.aliases]
# declare default aliases
"matplotlib.pyplot" = "plt"
numpy = "np"
pandas = "pd"
seaborn = "sns"
h5py = "h5"
scipy = "sp"

[lint.pycodestyle]
# ignore line-length violations for comments starting with task tags ("TODO", "FIXME")
ignore-overlong-task-comments = true
# max documentation line length
max-doc-length = 80
# max line length
max-line-length = 80

[lint.pydocstyle]
# set numpy convention
convention = "numpy"
