title: util-tools API
description: API documentation of the util-tools package

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

url: https://JVB11.github.io/AESolver/API_util_tools/
aux_links:
  Template Repository: https://github.com/JVB11/AESolver/API_util_tools/
